$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf
exec = gsettings set org.gnome.desktop.interface icon-theme 'One-Dark'
exec = gsettings set org.gnome.desktop.interface gtk-theme 'One-Dark'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

exec = hyprctl setcursor onedark-cursor 25
exec = gsettings set org.gnome.desktop.interface cursor-theme 'onedark-cursor'
exec = gsettings set org.gnome.desktop.interface cursor-size 25

general {
    gaps_in = 12
    gaps_out = 18
    border_size = 2
    col.active_border = rgba(61afefff)
    col.inactive_border = rgba(282c34aa)
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(61afefff)
    col.border_inactive = rgba(282c34aa)
    col.border_locked_active = rgba(61afefff)
    col.border_locked_inactive = rgba(282c34aa)
}

decoration {
    rounding = 17
    drop_shadow = true
    shadow_scale = 0.9
    shadow_ignore_window = true
    shadow_offset = 0 2
    shadow_range = 10
    shadow_render_power = 3
    col.shadow = rgba(00000055)
    col.shadow_inactive = rgba(00000022)

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur,waybar