# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml
[hyprland]
cursor_theme="onedark-cursor"
icon_theme="One-Dark"